name: Auto Merge PR to Default Branch

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Merge PR to Default Branch
      run: |
        PR_BRANCH=$(jq -r .pull_request.head.ref $GITHUB_EVENT_PATH)
        DEFAULT_BRANCH=$(jq -r .repository.default_branch $GITHUB_EVENT_PATH)

        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout "$DEFAULT_BRANCH"
        git merge --no-ff "$PR_BRANCH" -m "Auto-merge $PR_BRANCH to $DEFAULT_BRANCH"
        git push origin "$DEFAULT_BRANCH"
